### ISSUE TITLE
Add CSS animations to buttons

### ISSUE THREAD

**Issue by srinidhibhat45** [kan12340987/Tejas-SCL-maxo#41]

**Comment by srinidhibhat45** [comment]
@Shreyas12345678  can you look into this?

**Comment by Shreyas12345678** [comment]
yes srinidhi I  will look into it.

**Comment by Shreyas12345678** [comment]
Animation to all buttons we having it in website?

**Comment by srinidhibhat45** [comment]
> Animation to all buttons we having it in website?
>  

To the buttons on the secondary login page. The page displayed to the user once he has logged in

**Comment by Shreyas12345678** [comment]
yes,thanks

**Comment by srinidhibhat45** [comment]
resolved successfully by @Shreyas12345678
