### ISSUE TITLE
Remove Gap above dashboard

### ISSUE THREAD

**Issue by srinidhibhat45** [kan12340987/Tejas-SCL-maxo#7]
there is a lot of gap in the Dashboard section above the Dashboard which is un needed.

**Comment by 96RadhikaJadhav** [comment]
@srinidhibhat45 Could you please tell exactly where we need to remove the space?

**Comment by srinidhibhat45** [comment]
> @srinidhibhat45 Could you please tell exactly where we need to remove the space?

Hey @96RadhikaJadhav really appreciate you reaching out. This is actually supposed to be a 30 day hackathon project that me and 6 others are a part of. The repo is monitored so we can't accept PRs right now. Hope you understand 😊

**Comment by srinidhibhat45** [comment]
No longer applicable
